# ============================================
# Поддержка проекта KOSMOS
# ============================================

# Банковская карта для прямых переводов
custom: ["💳 Банковская карта: 2202 2023 1598 3324"]

# Альтернативные способы поддержки
github: # Пользователи GitHub могут стать спонсорами через GitHub Sponsors
  - Endlad2

# Подарки в Telegram
community_bridge: ["🎁 Telegram-подарки: @Endlad7373"]

# Наш Telegram чат
issuehunt: "https://t.me/+s5VjSehUEks3OGMy"
